CREATE TABLE `medical_record` (
    `id` INTEGER NOT NULL,
    `cid` INTEGER NOT NULL,
    `date` date NOT NULL,
    `case_name` TEXT  DEFAULT NULL,
    `diagnosis_name` TEXT  NOT NULL,
    `diagnosis_name_id` INTEGER NOT NULL,
    `affected_parts_id` INTEGER NOT NULL,
    `affected_parts` TEXT  NOT NULL,
    `diagnosed_by_name` TEXT  NOT NULL,
    `diagnosed_by_id` INTEGER NOT NULL,
    `drug_id` TEXT  NOT NULL,
    `drug_name` TEXT  NOT NULL,
    `dosage` TEXT  NOT NULL,
    `next_treatment_date` date NOT NULL,
    `ref` TEXT  NOT NULL,
    `ref_name` INTEGER NOT NULL,
    `ref_id` INTEGER NOT NULL,
    `description` text  NOT NULL,
    `learning` text 
    `priority` TEXT  NOT NULL,
    `reported_by_name` INTEGER NOT NULL,
    `reported_by` INTEGER NOT NULL,
    `route_id` INTEGER NOT NULL,
    `route_name` TEXT  NOT NULL,
    `image` TEXT  DEFAULT NULL,
    `doc` TEXT  DEFAULT NULL,
    `status` TEXT   NOT NULL DEFAULT 'P' ,
    `is_deleted` INTEGER NOT NULL DEFAULT '0' ,
    `created_by_name` TEXT  DEFAULT NULL ,
    `created_by` TEXT  DEFAULT NULL ,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `hide_ref` TEXT  NOT NULL,
    `hide_ref_id` TEXT  NOT NULL,
    PRIMARY KEY('id' AUTOINCREMENT)
    );